language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libfuse-dev
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew tap caskroom/cask && brew cask install osxfuse; fi
notifications:
  email:
    recipients:
      - pedro@pedrocr.net
    on_success: never
    on_failure: always
  irc:
    channels:
      - "irc.mozilla.org#chimper"
    on_success: always
    on_failure: always
    skip_join: true
