language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - libfuse-dev
notifications:
  email:
    recipients:
      - pedro@pedrocr.net
    on_success: never
    on_failure: always
  irc:
    channels:
      - "irc.mozilla.org#chimper"
    on_success: always
    on_failure: always
    skip_join: true
