language: rust
rust:
  - stable
  - beta
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libfuse-dev
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew cask install osxfuse; fi
notifications:
  email:
    recipients:
      - pedro@pedrocr.net
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.mozilla.org#chimper"
    on_success: change
    on_failure: always
    skip_join: true
if: tag IS blank
